Repository TImeCAlling/TImeCAlling_BE, pull requests merged in 2025-02, with the labels that each got.

#76 [FIX] 체크리스트 생성 오류 수정
  src/main/java/TImeCAlling/spring/service/schedule/checklist/ChecklistCommandServiceImpl.java
Labels: :wrench: fix

#77 [FEATURE/TEST] 깨우기 API
  build.gradle
  src/main/java/TImeCAlling/spring/config/FCMInitializer.java
  src/main/java/TImeCAlling/spring/repository/schedule/ScheduleRepository.java
  src/main/java/TImeCAlling/spring/repository/user/UserRepository.java
  src/main/java/TImeCAlling/spring/service/pushMessageNotification/PushNotificationCommandService.java
  src/main/java/TImeCAlling/spring/service/pushMessageNotification/PushNotificationCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/web/controller/pushMessageNotification/PushMessageNotificationController.java
  src/main/java/TImeCAlling/spring/web/dto/fcm/FcmMessageDTO.java
  src/main/java/TImeCAlling/spring/web/dto/pushMessageNotification/PushNotificationRequestDTO.java
  src/main/java/TImeCAlling/spring/web/dto/pushMessageNotification/PushNotificationResponseDTO.java
  src/main/resources/application.yml
  src/main/resources/firebase/firebase_service_key.json
Labels: :sparkles: feat, :test_tube: test

#78 [FIX] 토큰 재발급 API 오류 수정
  src/main/java/TImeCAlling/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/TImeCAlling/spring/apiPayload/exception/handler/.gitkeep
  src/main/java/TImeCAlling/spring/apiPayload/exception/handler/TokenHandler.java
  src/main/java/TImeCAlling/spring/auth/Handler/JwtAccessDeniedHandler.java
  src/main/java/TImeCAlling/spring/auth/Handler/JwtAuthenticationEntryPoint.java
  src/main/java/TImeCAlling/spring/auth/JwtUtil.java
  src/main/java/TImeCAlling/spring/auth/filter/JwtExceptionHandlerFilter.java
  src/main/java/TImeCAlling/spring/config/SecurityConfig.java
  src/main/java/TImeCAlling/spring/converter/user/UserConverter.java
  src/main/java/TImeCAlling/spring/service/user/UserCommandService.java
  src/main/java/TImeCAlling/spring/service/user/UserCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/web/controller/user/UserController.java
  src/main/java/TImeCAlling/spring/web/dto/user/UserRequestDTO.java
  src/main/java/TImeCAlling/spring/web/dto/user/UserResponseDTO.java
Labels: :wrench: fix

#80 [FEATURE/REFACTOR] 공유 일정 수정 옵션 추가
  src/main/java/TImeCAlling/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/TImeCAlling/spring/converter/schedule/RecurringScheduleConverter.java
  src/main/java/TImeCAlling/spring/converter/schedule/ScheduleConverter.java
  src/main/java/TImeCAlling/spring/repository/schedule/ScheduleRepository.java
  src/main/java/TImeCAlling/spring/service/schedule/RecurringScheduleService.java
  src/main/java/TImeCAlling/spring/service/schedule/RecurringScheduleServiceImpl.java
  src/main/java/TImeCAlling/spring/service/schedule/ScheduleCommandService.java
  src/main/java/TImeCAlling/spring/service/schedule/ScheduleCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/service/schedule/ScheduleQueryServiceImpl.java
  src/main/java/TImeCAlling/spring/service/schedule/checklist/ChecklistCommandService.java
  src/main/java/TImeCAlling/spring/service/schedule/checklist/ChecklistCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/web/controller/schedule/ScheduleController.java
  src/main/java/TImeCAlling/spring/web/dto/schedule/ScheduleRequestDTO.java
  src/test/java/TImeCAlling/spring/service/schedule/ScheduleCommandServiceTest.java
Labels: :chains: refactor, :sparkles: feat

#82 [CHORE] FCM 초기화 클래스 라이브러리 수정
  src/main/java/TImeCAlling/spring/config/FCMInitializer.java
Labels: :pencil2: chore

#83 [FIX/FEAT] 로그아웃 및 회원 탈퇴 API 구현
  src/main/java/TImeCAlling/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/TImeCAlling/spring/auth/JwtUtil.java
  src/main/java/TImeCAlling/spring/auth/filter/JwtExceptionHandlerFilter.java
  src/main/java/TImeCAlling/spring/config/SwaggerConfig.java
  src/main/java/TImeCAlling/spring/converter/user/UserConverter.java
  src/main/java/TImeCAlling/spring/service/user/UserCommandService.java
  src/main/java/TImeCAlling/spring/service/user/UserCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/service/user/UserDetailService.java
  src/main/java/TImeCAlling/spring/web/controller/user/UserController.java
  src/main/java/TImeCAlling/spring/web/dto/user/UserResponseDTO.java
  src/main/resources/application.yml
Labels: :sparkles: feat, :wrench: fix

#86 [FIX] 공유 일정 조회 시 닉네임 반환
  src/main/java/TImeCAlling/spring/converter/schedule/ScheduleConverter.java
  src/main/java/TImeCAlling/spring/web/controller/schedule/ScheduleController.java
Labels: :wrench: fix

#88 [FIX] DTO클래스명 중복으로 스웨거 스키마 표시가 잘못되는 오류 수정
  src/main/java/TImeCAlling/spring/service/schedule/checklist/ChecklistCommandService.java
  src/main/java/TImeCAlling/spring/service/schedule/checklist/ChecklistCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/web/controller/schedule/ChecklistController.java
  src/main/java/TImeCAlling/spring/web/dto/checklist/ChecklistRequestDTO.java
  src/test/java/TImeCAlling/spring/service/schedule/ChecklistCommandServiceTest.java
Labels: :wrench: fix

#89 [FEATURE&REFACTOR] 깨우기 API에서 다양한 멘트를 위한 코드 추가 및 수정
  src/main/java/TImeCAlling/spring/service/pushMessageNotification/PushDefaultMessage.java
  src/main/java/TImeCAlling/spring/service/pushMessageNotification/PushNotificationCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/web/controller/pushMessageNotification/PushMessageNotificationController.java
  src/main/java/TImeCAlling/spring/web/dto/fcm/FcmMessageDTO.java
  src/main/java/TImeCAlling/spring/web/dto/pushMessageNotification/PushNotificationRequestDTO.java
Labels: :chains: refactor, :sparkles: feat

#91 [FEATURE] Hibernate 2차 캐시 도입 & 일정 엔티티 조회 성능 최적화
  build.gradle
  src/main/java/TImeCAlling/spring/config/CacheConfig.java
  src/main/java/TImeCAlling/spring/domain/Schedule.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#95 [FIX] 반복 일정 관련 NullPointerException 에러 해결
  src/main/java/TImeCAlling/spring/service/schedule/ScheduleCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/validation/validator/EnumValidator.java
Labels: :wrench: fix

#93 [FEATURE] dev_CD.yml파일에 FIREBASE_SERVICE_KEY파일 생성 테스크 추가
  .github/workflows/dev_CD.yml
Labels: :construction_worker: cicd, :sparkles: feat

#99 [FIX] FCM 토큰 업데이트 관련 오류
  src/main/java/TImeCAlling/spring/web/controller/pushMessageNotification/PushMessageNotificationController.java
  src/main/java/TImeCAlling/spring/web/dto/fcm/FcmTokenRequestDTO.java
Labels: :page_facing_up: doc, :wrench: fix

#100 [HOTFIX] 깨우기 API JSON 관련 오류 수정
  src/main/java/TImeCAlling/spring/service/pushMessageNotification/PushNotificationCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/web/dto/pushMessageNotification/PushNotificationRequestDTO.java
  src/test/java/TImeCAlling/spring/service/pushNotification/PushNotificationCommandServiceTest.java
Labels: :wrench: fix

#101 [HOTFIX] Schedule이 의도치않게 여러 개가 되는 오류 수정
  src/main/java/TImeCAlling/spring/repository/schedule/ScheduleRepository.java
  src/main/java/TImeCAlling/spring/service/pushMessageNotification/PushNotificationCommandServiceImpl.java
Labels: :wrench: fix

#103 [FIX] 체크리스트 항목별 NULL 값 포함하도록 수정
  src/main/java/TImeCAlling/spring/domain/Checklist.java
  src/main/java/TImeCAlling/spring/domain/enums/External.java
  src/main/java/TImeCAlling/spring/domain/enums/Late.java
  src/main/java/TImeCAlling/spring/domain/enums/Reason.java
  src/main/java/TImeCAlling/spring/domain/enums/Spare.java
  src/main/java/TImeCAlling/spring/web/dto/checklist/ChecklistRequestDTO.java
Labels: :wrench: fix

#97 [CHORE] 준비중 일정 조회 API 비즈니스 로직 수정
  src/main/java/TImeCAlling/spring/converter/schedule/ScheduleConverter.java
  src/main/java/TImeCAlling/spring/web/controller/schedule/ScheduleController.java
Labels: :pencil2: chore

#110 [HOTFIX] 프로필 이미지 변경 시 파일 중복 확인 로직 추가
  src/main/java/TImeCAlling/spring/converter/user/UserConverter.java
  src/main/java/TImeCAlling/spring/service/s3/S3Service.java
  src/main/java/TImeCAlling/spring/service/user/UserCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/web/controller/user/UserController.java
Labels: :wrench: fix

#111 [FIX]: getIsWritten 값으로 체크하도록 변경
  src/main/java/TImeCAlling/spring/service/schedule/checklist/ChecklistCommandServiceImpl.java
Labels: :wrench: fix

#113 [FIX] failed 변수 할당 값 변경
  src/main/java/TImeCAlling/spring/converter/user/UserConverter.java
Labels: :wrench: fix
