Repository TImeCAlling/TImeCAlling_BE, pull requests merged in 2025-01, with the labels that each got.

#4 [CICD] yml환경 분리 및 CICD 구축
  .github/workflows/dev_CD.yml
  .github/workflows/dev_CI.yml
  src/main/resources/application.yml
Labels: :construction_worker: cicd

#6 [FEATURE] 도메인 클래스 작성 및 연관관계 매핑
  .github/workflows/dev_CI.yml
  src/main/java/TImeCAlling/spring/domain/Category.java
  src/main/java/TImeCAlling/spring/domain/ProfileImage.java
  src/main/java/TImeCAlling/spring/domain/PushMessage.java
  src/main/java/TImeCAlling/spring/domain/PushMessageSetting.java
  src/main/java/TImeCAlling/spring/domain/Schedule.java
  src/main/java/TImeCAlling/spring/domain/User.java
  src/main/java/TImeCAlling/spring/domain/enums/.gitkeep
  src/main/java/TImeCAlling/spring/domain/enums/External.java
  src/main/java/TImeCAlling/spring/domain/enums/Fit.java
  src/main/java/TImeCAlling/spring/domain/enums/FreeTime.java
  src/main/java/TImeCAlling/spring/domain/enums/Late.java
  src/main/java/TImeCAlling/spring/domain/enums/MessageStatus.java
  src/main/java/TImeCAlling/spring/domain/enums/Reason.java
  src/main/java/TImeCAlling/spring/domain/enums/RepeatDay.java
  src/main/java/TImeCAlling/spring/domain/enums/SocialType.java
  src/main/java/TImeCAlling/spring/domain/enums/Spare.java
  src/main/java/TImeCAlling/spring/domain/enums/Status.java
  src/main/java/TImeCAlling/spring/domain/enums/Success.java
  src/main/java/TImeCAlling/spring/domain/mapping/.gitkeep
  src/main/java/TImeCAlling/spring/domain/mapping/ScheduleCategory.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#10 [Feature] API 테스트를 위한 유저 CRUD 로직 수정
  src/main/java/TImeCAlling/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/TImeCAlling/spring/apiPayload/exception/handler/UserHandler.java
  src/main/java/TImeCAlling/spring/converter/user/UserConverter.java
  src/main/java/TImeCAlling/spring/domain/User.java
  src/main/java/TImeCAlling/spring/repository/user/UserRepository.java
  src/main/java/TImeCAlling/spring/service/.gitkeep
  src/main/java/TImeCAlling/spring/service/user/UserCommandService.java
  src/main/java/TImeCAlling/spring/service/user/UserCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/service/user/UserQueryService.java
  src/main/java/TImeCAlling/spring/service/user/UserQueryServiceImpl.java
  src/main/java/TImeCAlling/spring/web/controller/.gitkeep
  src/main/java/TImeCAlling/spring/web/controller/user/UserController.java
  src/main/java/TImeCAlling/spring/web/dto/.gitkeep
  src/main/java/TImeCAlling/spring/web/dto/user/UserRequestDTO.java
  src/main/java/TImeCAlling/spring/web/dto/user/UserResponseDTO.java
Labels: :sparkles: feat

#14 [FEATURE] 스프링 시큐리티 및 JWT 설정
  build.gradle
  src/main/java/TImeCAlling/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/TImeCAlling/spring/auth/Handler/JwtAccessDeniedHandler.java
  src/main/java/TImeCAlling/spring/auth/Handler/JwtAuthenticationEntryPoint.java
  src/main/java/TImeCAlling/spring/auth/Handler/JwtExceptionHandler.java
  src/main/java/TImeCAlling/spring/auth/JwtUtil.java
  src/main/java/TImeCAlling/spring/auth/filter/JwtAuthenticationFilter.java
  src/main/java/TImeCAlling/spring/auth/filter/JwtExceptionHandlerFilter.java
  src/main/java/TImeCAlling/spring/config/SecurityConfig.java
  src/main/java/TImeCAlling/spring/domain/User.java
  src/main/java/TImeCAlling/spring/repository/user/UserRepository.java
  src/main/java/TImeCAlling/spring/service/user/UserDetailService.java
  src/main/java/TImeCAlling/spring/web/controller/TokenController.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#15 [FEATURE&TEST] 푸시 메세지 세팅 CRUD 및 단위 테스트 구현
  src/main/java/TImeCAlling/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/TImeCAlling/spring/apiPayload/exception/handler/PushMessageSettingHandler.java
  src/main/java/TImeCAlling/spring/converter/pushMessageSetting/PushMessageSettingConverter.java
  src/main/java/TImeCAlling/spring/domain/PushMessageSetting.java
  src/main/java/TImeCAlling/spring/repository/pushMessageSetting/PushMessageSettingRepository.java
  src/main/java/TImeCAlling/spring/repository/pushMessageSetting/PushMessageSettingRepositoryCustom.java
  src/main/java/TImeCAlling/spring/repository/pushMessageSetting/PushMessageSettingRepositoryCustomImpl.java
  src/main/java/TImeCAlling/spring/service/pushMessageSetting/PushMessageSettingCommandService.java
  src/main/java/TImeCAlling/spring/service/pushMessageSetting/PushMessageSettingCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/service/pushMessageSetting/PushMessageSettingQueryService.java
  src/main/java/TImeCAlling/spring/service/pushMessageSetting/PushMessageSettingQueryServiceImpl.java
  src/main/java/TImeCAlling/spring/web/controller/pushMessageSetting/PushMessageSettingController.java
  src/main/java/TImeCAlling/spring/web/dto/pushMessageSetting/PushMessageSettingRequestDTO.java
  src/main/java/TImeCAlling/spring/web/dto/pushMessageSetting/PushMessageSettingResponseDTO.java
  src/test/java/TImeCAlling/spring/repository/PushMessageSettingRepositoryTest.java
  src/test/java/TImeCAlling/spring/service/pushMessageSetting/PushMessageSettingCommandServiceTest.java
Labels: :sparkles: feat, :test_tube: test

#25 [FEATURE] 일정 CRUD
  src/main/java/TImeCAlling/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/TImeCAlling/spring/apiPayload/exception/handler/ScheduleHandler.java
  src/main/java/TImeCAlling/spring/converter/schedule/ScheduleConverter.java
  src/main/java/TImeCAlling/spring/domain/Category.java
  src/main/java/TImeCAlling/spring/domain/Schedule.java
  src/main/java/TImeCAlling/spring/domain/User.java
  src/main/java/TImeCAlling/spring/domain/mapping/ScheduleCategory.java
  src/main/java/TImeCAlling/spring/repository/schedule/CategoryRepository.java
  src/main/java/TImeCAlling/spring/repository/schedule/ScheduleRepository.java
  src/main/java/TImeCAlling/spring/service/schedule/ScheduleCommandService.java
  src/main/java/TImeCAlling/spring/service/schedule/ScheduleCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/service/schedule/ScheduleQueryService.java
  src/main/java/TImeCAlling/spring/service/schedule/ScheduleQueryServiceImpl.java
  src/main/java/TImeCAlling/spring/service/user/UserQueryService.java
  src/main/java/TImeCAlling/spring/service/user/UserQueryServiceImpl.java
  src/main/java/TImeCAlling/spring/validation/annotation/ExistSchedule.java
  src/main/java/TImeCAlling/spring/validation/annotation/ValidEnum.java
  src/main/java/TImeCAlling/spring/validation/validator/EnumValidator.java
  src/main/java/TImeCAlling/spring/validation/validator/ExistScheduleValidator.java
  src/main/java/TImeCAlling/spring/web/controller/schedule/ScheduleController.java
  src/main/java/TImeCAlling/spring/web/dto/schedule/ScheduleRequestDTO.java
  src/main/java/TImeCAlling/spring/web/dto/schedule/ScheduleResponseDTO.java
Labels: :sparkles: feat

#27 [FEATURE] 엔티티 구조 변경 및 반복일정 처리 로직구현
  src/main/java/TImeCAlling/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/TImeCAlling/spring/converter/schedule/RecurringScheduleConverter.java
  src/main/java/TImeCAlling/spring/converter/schedule/ScheduleConverter.java
  src/main/java/TImeCAlling/spring/domain/Checklist.java
  src/main/java/TImeCAlling/spring/domain/RecurringSchedule.java
  src/main/java/TImeCAlling/spring/domain/Schedule.java
  src/main/java/TImeCAlling/spring/domain/enums/Fit.java
  src/main/java/TImeCAlling/spring/domain/enums/RepeatDay.java
  src/main/java/TImeCAlling/spring/domain/enums/Success.java
  src/main/java/TImeCAlling/spring/repository/schedule/ChecklistRepository.java
  src/main/java/TImeCAlling/spring/repository/schedule/RecurringScheduleRepository.java
  src/main/java/TImeCAlling/spring/repository/user/UserRepository.java
  src/main/java/TImeCAlling/spring/service/schedule/ChecklistService.java
  src/main/java/TImeCAlling/spring/service/schedule/ChecklistServiceImpl.java
  src/main/java/TImeCAlling/spring/service/schedule/RecurringScheduleService.java
  src/main/java/TImeCAlling/spring/service/schedule/RecurringScheduleServiceImpl.java
  src/main/java/TImeCAlling/spring/service/schedule/ScheduleCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/service/schedule/ScheduleQueryServiceImpl.java
  src/main/java/TImeCAlling/spring/service/user/UserDetailService.java
  src/main/java/TImeCAlling/spring/validation/annotation/.gitkeep
  src/main/java/TImeCAlling/spring/validation/validator/.gitkeep
  src/main/java/TImeCAlling/spring/validation/validator/EnumValidator.java
  src/main/java/TImeCAlling/spring/web/controller/schedule/ScheduleController.java
  src/main/java/TImeCAlling/spring/web/dto/schedule/ScheduleRequestDTO.java
  src/main/java/TImeCAlling/spring/web/dto/schedule/ScheduleResponseDTO.java
Labels: :pencil2: chore, :sparkles: feat

#32 [Feature] 나의 일정 현황 조회 API 구현
  src/main/java/TImeCAlling/spring/converter/user/UserConverter.java
  src/main/java/TImeCAlling/spring/domain/User.java
  src/main/java/TImeCAlling/spring/web/controller/schedule/ScheduleController.java
  src/main/java/TImeCAlling/spring/web/dto/schedule/ScheduleResponseDTO.java
Labels: :sparkles: feat

#36 [FEATURE] 체크리스트 작성 API
  src/main/java/TImeCAlling/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/TImeCAlling/spring/apiPayload/exception/handler/ChecklistHandler.java
  src/main/java/TImeCAlling/spring/converter/schedule/ChecklistConverter.java
  src/main/java/TImeCAlling/spring/domain/Checklist.java
  src/main/java/TImeCAlling/spring/domain/User.java
  src/main/java/TImeCAlling/spring/domain/enums/External.java
  src/main/java/TImeCAlling/spring/domain/enums/Late.java
  src/main/java/TImeCAlling/spring/domain/enums/Reason.java
  src/main/java/TImeCAlling/spring/domain/enums/Spare.java
  src/main/java/TImeCAlling/spring/repository/schedule/ChecklistRepository.java
  src/main/java/TImeCAlling/spring/service/schedule/ScheduleCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/service/schedule/checklist/ChecklistCommandService.java
  src/main/java/TImeCAlling/spring/service/schedule/checklist/ChecklistCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/service/schedule/checklist/ChecklistQueryService.java
  src/main/java/TImeCAlling/spring/service/schedule/checklist/ChecklistQueryServiceImpl.java
  src/main/java/TImeCAlling/spring/web/controller/schedule/ChecklistController.java
  src/main/java/TImeCAlling/spring/web/controller/schedule/ScheduleController.java
  src/main/java/TImeCAlling/spring/web/dto/checklist/ChecklistRequestDTO.java
  src/main/java/TImeCAlling/spring/web/dto/checklist/ChecklistResponseDTO.java
  src/test/java/TImeCAlling/spring/service/schedule/ChecklistCommandServiceTest.java
Labels: :sparkles: feat

#38 [FEATURE] 작성 완료된 체크리스트 날짜 지나면 삭제하는 기능 구현
  src/main/java/TImeCAlling/spring/Application.java
  src/main/java/TImeCAlling/spring/repository/schedule/ChecklistRepository.java
  src/main/java/TImeCAlling/spring/service/schedule/checklist/ChecklistCommandService.java
  src/main/java/TImeCAlling/spring/service/schedule/checklist/ChecklistCommandServiceImpl.java
Labels: :sparkles: feat

#43 [FEATURE&TEST] FCM 토큰을 저장하는 API
  build.gradle
  src/main/java/TImeCAlling/spring/domain/User.java
  src/main/java/TImeCAlling/spring/service/pushMessageNotification/PushNotificationCommandService.java
  src/main/java/TImeCAlling/spring/service/pushMessageNotification/PushNotificationCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/web/controller/pushMessageNotification/PushMessageNotificationController.java
  src/main/java/TImeCAlling/spring/web/dto/fcm/FcmTokenRequestDTO.java
  src/main/java/TImeCAlling/spring/web/dto/fcm/FcmTokenResponseDTO.java
  src/test/java/TImeCAlling/spring/service/pushNotification/PushNotificationCommandServiceTest.java
Labels: :sparkles: feat, :test_tube: test

#42 [FEATURE] 카카오 회원가입 및 로그인 구현
  build.gradle
  src/main/java/TImeCAlling/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/TImeCAlling/spring/auth/JwtUtil.java
  src/main/java/TImeCAlling/spring/config/SecurityConfig.java
  src/main/java/TImeCAlling/spring/config/SwaggerConfig.java
  src/main/java/TImeCAlling/spring/converter/.gitkeep
  src/main/java/TImeCAlling/spring/converter/user/ProfileImageConverter.java
  src/main/java/TImeCAlling/spring/converter/user/UserConverter.java
  src/main/java/TImeCAlling/spring/domain/User.java
  src/main/java/TImeCAlling/spring/repository/.gitkeep
  src/main/java/TImeCAlling/spring/repository/user/ProfileImageRepository.java
  src/main/java/TImeCAlling/spring/repository/user/UserRepository.java
  src/main/java/TImeCAlling/spring/service/user/UserCommandService.java
  src/main/java/TImeCAlling/spring/service/user/UserCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/service/user/UserDetailService.java
  src/main/java/TImeCAlling/spring/web/controller/TokenController.java
  src/main/java/TImeCAlling/spring/web/controller/user/UserController.java
  src/main/java/TImeCAlling/spring/web/dto/user/UserAuthDTO.java
  src/main/java/TImeCAlling/spring/web/dto/user/UserRequestDTO.java
  src/main/java/TImeCAlling/spring/web/dto/user/UserResponseDTO.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#45 [Chore] 체크리스트 작성 API 요청 값 변경 (유저 id -> 토큰)
  src/main/java/TImeCAlling/spring/web/controller/schedule/ChecklistController.java
Labels: :pencil2: chore

#50 [REFACTOR&DOCS] 일정 멤버 조회 API, FCM 토큰 업데이트 API User관련 로직 개선 및 스웨거 명세 추가
  src/main/java/TImeCAlling/spring/web/controller/pushMessageNotification/PushMessageNotificationController.java
  src/main/java/TImeCAlling/spring/web/controller/schedule/ScheduleController.java
  src/main/java/TImeCAlling/spring/web/dto/fcm/FcmTokenRequestDTO.java
Labels: :chains: refactor, :page_facing_up: doc

#46 [FEATURE] 스웨거 페이지 API 명세 작성 및 특정 날짜 일정 조회 API 로직 수정
  src/main/java/TImeCAlling/spring/converter/schedule/ScheduleConverter.java
  src/main/java/TImeCAlling/spring/repository/schedule/ChecklistRepository.java
  src/main/java/TImeCAlling/spring/service/schedule/checklist/ChecklistCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/web/controller/schedule/ScheduleController.java
  src/main/java/TImeCAlling/spring/web/dto/schedule/ScheduleResponseDTO.java
Labels: :page_facing_up: doc, :pencil2: chore

#49 [FEATURE] 오늘 일정 목록 조회 API 추가
  src/main/java/TImeCAlling/spring/converter/schedule/ScheduleConverter.java
  src/main/java/TImeCAlling/spring/service/schedule/checklist/ChecklistCommandService.java
  src/main/java/TImeCAlling/spring/service/schedule/checklist/ChecklistCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/service/schedule/checklist/ChecklistQueryService.java
  src/main/java/TImeCAlling/spring/service/schedule/checklist/ChecklistQueryServiceImpl.java
  src/main/java/TImeCAlling/spring/web/controller/schedule/ScheduleController.java
  src/main/java/TImeCAlling/spring/web/dto/schedule/ScheduleResponseDTO.java
Labels: :sparkles: feat

#53 [DOCS] 체크리스트 작성 API 스웨거 명세서 추가
  src/main/java/TImeCAlling/spring/web/controller/schedule/ChecklistController.java
Labels: :page_facing_up: doc

#55 [FEATURE] checklist 테이블에 대한 DB 인덱스 추가
  src/main/java/TImeCAlling/spring/domain/Checklist.java
Labels: :sparkles: feat

#58 [REFACTOR] 일정 CRUD 토큰 적용 및 스웨거 명세 작성
  src/main/java/TImeCAlling/spring/web/controller/schedule/ScheduleController.java
Labels: :chains: refactor, :page_facing_up: doc

#66 [CHORE] 일정 목록 조회 API 응답에 scheduleId 추가
  src/main/java/TImeCAlling/spring/converter/schedule/ScheduleConverter.java
  src/main/java/TImeCAlling/spring/web/dto/schedule/ScheduleResponseDTO.java
  src/test/java/TImeCAlling/spring/service/schedule/ScheduleCommandServiceTest.java
Labels: :chains: refactor, :pencil2: chore

#62 [REFACTOR] 일정 상세 조회 시 checklistId 사용
  src/main/java/TImeCAlling/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/TImeCAlling/spring/converter/schedule/ScheduleConverter.java
  src/main/java/TImeCAlling/spring/repository/schedule/ScheduleRepository.java
  src/main/java/TImeCAlling/spring/service/schedule/ScheduleQueryService.java
  src/main/java/TImeCAlling/spring/service/schedule/ScheduleQueryServiceImpl.java
  src/main/java/TImeCAlling/spring/validation/annotation/ExistChecklist.java
  src/main/java/TImeCAlling/spring/validation/validator/ExistChecklistValidator.java
  src/main/java/TImeCAlling/spring/web/controller/schedule/ScheduleController.java
  src/main/java/TImeCAlling/spring/web/dto/schedule/ScheduleRequestDTO.java
  src/main/java/TImeCAlling/spring/web/dto/schedule/ScheduleResponseDTO.java
Labels: :chains: refactor

#61 [DOCS] 회원 CRUD 스웨거 명세서 작성
  src/main/java/TImeCAlling/spring/web/controller/user/UserController.java
Labels: :page_facing_up: doc

#68 [CHORE] 프로필 이미지 CRUD 수정
  src/main/java/TImeCAlling/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/TImeCAlling/spring/config/MultipartJackson2HttpMessageConverter.java
  src/main/java/TImeCAlling/spring/converter/user/ProfileImageConverter.java
  src/main/java/TImeCAlling/spring/converter/user/UserConverter.java
  src/main/java/TImeCAlling/spring/domain/ProfileImage.java
  src/main/java/TImeCAlling/spring/domain/User.java
  src/main/java/TImeCAlling/spring/repository/user/ProfileImageRepository.java
  src/main/java/TImeCAlling/spring/service/user/UserCommandService.java
  src/main/java/TImeCAlling/spring/service/user/UserCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/web/controller/user/UserController.java
  src/main/java/TImeCAlling/spring/web/dto/user/UserRequestDTO.java
  src/main/java/TImeCAlling/spring/web/dto/user/UserResponseDTO.java
Labels: :pencil2: chore, :sparkles: feat

#69 [REFACTOR&DOCS] 푸시메세지 CRUD API 관련 이름 전체 변경 및 스웨거 명세 추가
  src/main/java/TImeCAlling/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/TImeCAlling/spring/apiPayload/exception/handler/AlarmListHandler.java
  src/main/java/TImeCAlling/spring/converter/alarmList/AlarmListConverter.java
  src/main/java/TImeCAlling/spring/converter/pushMessageSetting/PushMessageSettingConverter.java
  src/main/java/TImeCAlling/spring/domain/Alarm.java
  src/main/java/TImeCAlling/spring/domain/AlarmList.java
  src/main/java/TImeCAlling/spring/domain/User.java
  src/main/java/TImeCAlling/spring/repository/alarmList/AlarmListRepository.java
  src/main/java/TImeCAlling/spring/repository/alarmList/AlarmListRepositoryCustom.java
  src/main/java/TImeCAlling/spring/repository/alarmList/AlarmListRepositoryCustomImpl.java
  src/main/java/TImeCAlling/spring/repository/pushMessageSetting/PushMessageSettingRepository.java
  src/main/java/TImeCAlling/spring/repository/pushMessageSetting/PushMessageSettingRepositoryCustom.java
  src/main/java/TImeCAlling/spring/service/alarmList/AlarmListCommandService.java
  src/main/java/TImeCAlling/spring/service/alarmList/AlarmListCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/service/alarmList/AlarmListQueryService.java
  src/main/java/TImeCAlling/spring/service/alarmList/AlarmListQueryServiceImpl.java
  src/main/java/TImeCAlling/spring/service/pushMessageSetting/PushMessageSettingCommandService.java
  src/main/java/TImeCAlling/spring/service/pushMessageSetting/PushMessageSettingCommandServiceImpl.java
  src/main/java/TImeCAlling/spring/service/pushMessageSetting/PushMessageSettingQueryService.java
  src/main/java/TImeCAlling/spring/service/pushMessageSetting/PushMessageSettingQueryServiceImpl.java
  src/main/java/TImeCAlling/spring/web/controller/alarmList/AlarmController.java
  src/main/java/TImeCAlling/spring/web/controller/pushMessageSetting/PushMessageSettingController.java
  src/main/java/TImeCAlling/spring/web/dto/alarmList/AlarmListRequestDTO.java
  src/main/java/TImeCAlling/spring/web/dto/alarmList/AlarmListResponseDTO.java
  src/test/java/TImeCAlling/spring/repository/AlarmListRepositoryTest.java
  src/test/java/TImeCAlling/spring/service/pushMessageSetting/PushMessageSettingCommandServiceTest.java
Labels: :chains: refactor, :page_facing_up: doc

#72 [REFACTOR] 일정 API response 수정
  src/main/java/TImeCAlling/spring/converter/schedule/ScheduleConverter.java
  src/main/java/TImeCAlling/spring/web/controller/schedule/ScheduleController.java
  src/main/java/TImeCAlling/spring/web/dto/schedule/ScheduleResponseDTO.java
Labels: :chains: refactor
